apps/admin/urls.py
from django.conf.urls import url,include
from ..admin.views import employee_add,employee_list,employee_delete,employee_edit,PromedioList,add_porcentaje,PromedioDelete

urlpatterns = [
    url(r'^index$', employee_list, name='employee_list'),
    url(r'^add$', employee_add, name="employee_add"),
    #url('<int:id>/details/', employee_details, name="employee_details"),
    url(r'^edit/(?P<id>\d+)/$', employee_edit, name="employee_edit"),
    #url(r'^edit/(?P<id_admin>\d+)/$', employee_edit, name='employee_edit'),
    url(r'^delete/(?P<id>\d+)/$', employee_delete, name="employee_delete"),

    #prmedio
    url(r'^listar$', PromedioList.as_view(), name='promedio_listar'),
    url(r'^nuevo/$',add_porcentaje, name='porcentaje_crear'),
    # url(r'^add/$', views.add_porcentaje, name='padd'),
    url(r'^eliminar/(?P<pk>\d+)/$', PromedioDelete.as_view(), name='promedio_eliminar'),
]

apps/contratos_largos/urls.py
from django.conf.urls import url,include
from .ajax import get_municipios
from django.contrib.auth.decorators import login_required
from ..contratos_largos.views import index,select_view,selectcor_view,contrato_delete,contrato_edit,modificarmodal, \
    ContratoList,ContratoCrear,ContratoUpdate,ContratoDelete,search,principal,ContratoCrearCorto,ReporteViaticosEmp,buscar,login_request

from .views import buscar,buscar1,buscarContrato,ReportAnual

urlpatterns = [
    url(r'^$', login_required(index),name='index'),
    url(r'^nuevo$', login_required(select_view), name='contratolargo_crear'),
    url(r'^nuevocorto$', login_required(selectcor_view), name='contratolargo_crear_corto'),
    url(r'^buscar/$',login_required(search), name='buscar'),
    url(r'^buscarClas/$',login_required(buscar.as_view()), name='buscarClas'),
    url(r'^buscarUsr/$',login_required(buscar1.as_view()), name='buscarUsr'),
    url(r'^principal/',login_required(principal), name='principal'),

    url(r'^eliminar/(?P<pk>\d+)/$', login_required(ContratoDelete.as_view()), name='contratolargo_eliminar'),
    url(r'^editar/(?P<id_contratolargo>\d+)/$', login_required(contrato_edit), name='contratolargo_actualizar'),
    url(r'^ajax/get_municipios/$', login_required(get_municipios), name='get_municipios'),
    url(r'^mod/(?P<id_contratolargo>\d+)/$',login_required(modificarmodal), name='modificar'),
    url(r'^buscarContrato/$',login_required(buscarContrato),name='buscarContrato'),
    url(r'^reporte/(?P<idlugar>[-\w]+)/(?P<idfecha_inicial>[-\w]+)/(?P<idfecha_final>[-\w]+)/$', ReporteViaticosEmp.as_view(), name='reportes'),
    url(r'^reportes/(?P<idlugar>[-\w]+)/(?P<idfecha_inicial>.+?)/(?P<idfecha_final>.+?)/$', login_required(ReportAnual.as_view()), name='reporte_anual_operador'),    

]

apps/usuario/urls.py
from django.conf.urls import url
from ..usuario.views import RegistroUsuario
from django.contrib.auth.decorators import login_required
from .views import user_edit
urlpatterns =[
    url(r'^registrar', login_required(RegistroUsuario.as_view()), name="registrar"),
    url(r'^editar/(?P<id_user>\d+)/$', login_required(user_edit), name='usuario_actualizar'),

]

reservas/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib import admin
from apps.contratos_largos.views import login_request
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login,logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete

urlpatterns = [
    url(r'^$',RedirectView.as_view(pattern_name='login',permanent=False)),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login_request, name='login'),
    url(r'^contratolargo/', include('apps.contratos_largos.urls', namespace="contratolargo")),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
    url(r'^admin/', include('apps.admin.urls', namespace="administrador")),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        {% block meta %}
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <title style=" font-family: 'Agency FB', arial;">G.A.D.P.</title>
        {% load staticfiles %}
        {% block stylesheets %}
            <!-- JQVMap -->

            <!--<script src="/static/vendors/js/jquery-3.3.1.slim.min.js"></script>-->
            <!--<script src="/static/vendors/js/jquery.min.js"></script>
            <script src="/static/vendors/js/bootstrap.min.js"></script>-->
            <link rel="stylesheet" href="{% static "vendors/fuenteCss/agency-fb.css " %}">
            <!--<link rel="stylesheet" href="/static/vendors/fuenteCss/agency-fb.css">-->

            <!--<link href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css" rel="stylesheet"/>-->

            <link rel="stylesheet" href="{% static "vendors/tablas/jquery.dataTables.min.css" %}">


            <!--<link rel="stylesheet" href="{% static "vendors/jqvmap/dist/jqvmap.min.css" %}">-->



            <!--<link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>-->
            <!-- Bootstrap -->
            <link rel="stylesheet" href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}">
            <!-- <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">-->
            <!-- Font Awesome -->
            <link rel="stylesheet" href="{% static "vendors/fonts/css/fontawesome.min.css" %}">
            <!--<link href="/static/vendors/fonts/css/fontawesome.min.css" rel="stylesheet" >-->

            <!-- NProgress -->
            <link rel="stylesheet" href="{% static "vendors/nprogress/nprogress.css" %}">
            <!--<link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">-->
            <!-- bootstrap-daterangepicker -->
            <!-- iCheck -->

            <!--<link rel="stylesheet" href="{% static " vendors/iCheck/skins/flat/green.css" %}">-->

            <!--<link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">-->
            <!-- bootstrap-progressbar -->
            <link rel="stylesheet"
                  href="{% static "vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" %}">
            <!--<link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">-->
            <link rel="stylesheet" href="{% static "vendors/css/bootstrap-datetimepicker.min.css" %}">
            <!--<link href="/static/vendors/css/bootstrap-datetimepicker.min.css" rel="stylesheet">-->
            <link rel="stylesheet" href="{% static "vendors/css/bootstrap-datepicker.min.css" %}">
            <!-- <link rel="stylesheet" href="/static/vendors/css/bootstrap-datepicker.min.css">-->
            <link rel="shortcut icon" href="{% static 'images/gobernacionprincipal.png' %}"/>
            <!--<link rel="stylesheet" href="/static/vendors/datetimepicker-jquery/jquery.datetimepicker.min.css">-->
        {% endblock stylesheets %}
        <!-- Custom Theme Style -->

        <link href="/static/vendors/css/custom.css" rel="stylesheet">
    {% endblock head %}
</head>
<body class="{% block body_class %}nav-md {% endblock body_class %}">
{% block body %}
    <div class="container body">
        <div class="main_container">
            {% block sidebar %}
                <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
                    {% include "base/sidebar.html" %}
                </div>
            {% endblock sidebar %}
            {% block top_navigation %}
                <div class="top_nav">
                    {% include "base/top_navigation.html" %}
                </div>
            {% endblock top_navigation %}
            {% block content %}

                <!-- {{ content }} -->
            {% endblock content %}
            {% block footer %}
                <footer>
                    {% include "base/footer.html" %}
                </footer>
            {% endblock footer %}
        </div>
    </div>
    {% block javascripts %}
        <!-- jQuery -->
        <script src="{% static "vendors/jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "vendors/blockUI/jquery.blockUI.js" %}"></script>
        <script src="{% static "vendors/js/paginator.js" %}"></script>
        <!-- Bootstrap -->
        <script src="{% static "vendors/bootstrap/dist/js/bootstrap.js" %}"></script>
        <!-- NProgress -->
        <script src="{% static "vendors/nprogress/nprogress.js" %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static "vendors/bootstrap-progressbar/bootstrap-progressbar.min.js" %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static "vendors/tablas/jquery.dataTables.min.js" %}"></script>
        <!-- <script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>-->
        <script src="{% static "vendors/fonts/all.js" %}"></script>
        <!--<script src="/static/vendors/fonts/all.js"></script>-->
        <script src="{% static "vendors/moment/min/moment.min.js" %}"></script>
        <!--script para las notificaciones -->
        <script src="{% static "vendors/google-code-prettify/src/prettify.js" %}"></script>
        <!-- Autosize -->
        <script src="{% static "vendors/autosize/dist/autosize.min.js" %}"></script>
        <!--<script src="/static/vendors/autosize/dist/autosize.min.js"></script> -->
        <script src="{% static "vendors/js/es.js" %}"></script>
        <!--<script src="/static/vendors/js/es.js"></script> -->
        <script src="{% static "vendors/js/bootstrap-datetimepicker.min.js" %}"></script>
        <script src="{% static "vendors/js/bootstrap-datepicker.min.js" %}"></script>

        <script src="{% static "vendors/js/bootstrap-datepicker.es.js " %}"></script>
        <script src="{% static "vendors/js/vfs_fonts.js" %}"></script>
        <script type="text/javascript">
            $(function () {
                $('.date').datetimepicker({});

            });
        </script>
        <script type="text/javascript">
            $(function () {
                $('#datein').datetimepicker({
                    format: 'DD/MM/YYYY HH:mm',
                });
                $('#datede').datetimepicker({
                    format: 'DD/MM/YYYY HH:mm',
                });
                $('#datefi').datetimepicker({

                    format: 'DD/MM/YYYY HH:mm',
                });
            });
        </script>

        <script type="text/javascript">
            $(function () {
                $('.filtrar').datepicker({
                    format: 'dd/mm/yyyy',
                    language: 'es',
                    autoclose: true,
                });
                var getDate = function (input) {
                    return new Date(input.date.valueOf());
                };
                $('.entrada, .salida,.datepicker').datepicker({
                    format: 'dd/mm/yyyy',
                    language: 'es',
                    autoclose: true,

                });

                $('.salida').datepicker({
                    startDate: '+6d',
                    endDate: '+36d',
                });

                $('.entrada').datepicker({
                    startDate: '+5d',
                    endDate: '+35d',
                }).on('changeDate',
                    function (selected) {
                        $('.salida').datepicker('clearDates');
                        $('.salida').datepicker('setStartDate', getDate(selected));
                    });

            })
        </script>
        <script>
            $(document).ready(function () {
                // messages timeout for 3 sec
                setTimeout(function () {
                    $('.message').fadeOut('slow');
                }, 3000); // <-- time in milliseconds, 1000 =  1 sec
            });
        </script>
        <script type="text/javascript">
            $(function miFuncion() {
                $('#datetimepicker6').datetimepicker({
                    format: 'DD/MM/YYYY HH:mm',


                });
                $('#datetimepicker7').datetimepicker({
                    format: 'DD/MM/YYYY HH:mm',
                    useCurrent: false //Important! See issue #1075
                });
                $("#datetimepicker6").on("dp.change", function (e) {
                    $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
                });
                $("#datetimepicker7").on("dp.change", function (e) {
                    $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
                });
            });
        </script>
        <script>
            $(document).ready(function () {
                $('#loader').click(function () {
                    $.blockUI({
                        message: '<h1><img  src="/static/images/preload.gif" /> Just a moment...</h1>',
                        css: {
                            border: 'none',
                            padding: '15px',
                            backgroundColor: '#000',
                            '-webkit-border-radius': '10px',
                            '-moz-border-radius': '10px',
                            opacity: .5,
                            color: '#fff'
                        }
                    });

                    setTimeout($.unblockUI, 2000);
                });
                $('#preload').click(function () {
                    $.blockUI({message: '<h><img style="width: 60; height: 60;" src="/static/images/loading.gif" /> Espere un momento...</h>'});

                });
                $('.preload').click(function () {
                    $.blockUI({message: '<h><img style="width: 60; height: 60;" src="/static/images/loading.gif" /> Espere un momento...</h>'});

                });

            });


        </script>
        <script type="text/javascript">

            $(document).ready(function () {

                var height = $(window).height();

                $('#altototal').height(height);
            });

        </script>

    {% endblock %}
    <!-- Custom Theme Scripts -->
    <script src="/static/vendors/js/custom.js"></script>
{% endblock body %}
</body>
</html>

templates/base/footer.html
<div  class="pull-right" >
 <a> Gobierno Autonomo Departamental De Potosi </a>
</div>
<div class="clearfix"></div>

templates/base/sidebar.html
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="{% url 'contratolargo:principal' %}" class="site_title">&nbsp<i class="fa fa-home"></i> <span>&nbsp G.A.D.P</span></a>

    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
        <div class="profile_pic">
            <img src="/static/images/gobierno.png" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
            <span>BIENVENIDO</span>
            <h2>{{ user.first_name }} <br>{{ user.last_name }} </h2>
        </div>
    </div>
    <!-- /menu profile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <h3>Inicio</h3>

            <ul class="nav side-menu">
                <!--<li><a><i class="fa fa-home"></i> Ubicacion <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                        <li><a href="index2.html">IV centenario</a></li>
                    <li><a href="index3.html">Ex terminal</a></li>
                        <li><a href="index2.html">Los pinos</a></li>

                    <li><a href="index3.html">SE.DE.DE.</a></li>
                    <li><a href="index2.html">Secretaria departamental de Turismo</a></li>
                    <li><a href="index3.html">Secretaria departamental de Mineria</a></li>
                    <li><a href="index2.html">Ventanilla Unica</a></li>
                    <li><a href="index2.html">IDTGB</a></li>
                        <li><a href="index3.html">Edificio Ex Sedes (Estacionamiento)</a></li>
                    <li><a href="index3.html">Unidad de Transporte</a></li>
                    <li><a href="index2.html">Secretaria Departamental de Desarrollo Agropecuario</a></li>
                    <li><a href="index3.html">Activos Fijos</a></li>
                  </ul>-->
                </li>
                {% if user.is_authenticated %}
                    {% if perms.contratos_largos.Registrar %}
                        <li>
                        <a><i class="fa fa-edit"><br></i>&nbsp&nbsp &nbsp Formularios &nbsp&nbsp &nbsp &nbsp &nbsp &nbsp
                            &nbsp &nbsp &nbsp &nbsp <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            {% if user.is_authenticated %}
                                {% if user.is_superuser %}
                                {% endif %}
                            {% endif %}

                            <li><a href="{% url 'contratolargo:contratolargo_crear' %}">Contrato</a></li>

                            <li><a href="{% url 'contratolargo:contratolargo_crear_corto' %}">Reservas</a></li>


                        </ul>
                    {% endif %}
                {% endif %}

                <li><a><i class="fa fa-user"></i>&nbsp&nbsp &nbsp Registros &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                    &nbsp&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        {% if user.is_authenticated %}
                            {% if perms.contratos_largos.ver_formLic %}
                                <li><a href="{% url 'contratolargo:buscarClas' %}">Vista Encargada</a></li>
                            {% endif %}
                        {% endif %}
                        {% if user.is_authenticated %}
                            {% if perms.contratos_largos.ver_formUsr %}
                                <li><a href="{% url 'contratolargo:buscarUsr' %}">Vista Usuarios</a></li>
                            {% endif %}
                        {% endif %}
                    </ul>
                </li>
                <!-- {% if user.is_authenticated %}
            {% if user.is_superuser %}
          
               <li><a><i class="fa fa-user"></i>&nbsp&nbsp &nbsp Usuarios  &nbsp&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a  href="{% url 'administrador:employee_add' %}">Añadir </a></li>
                    <li><a  href="{% url 'administrador:employee_list' %}">Listar </a></li>
                
              </li>
            {% endif %}
          {% endif %} -->


            </ul>
        </div>
    </div>
    <!-- /sidebar menu -->
</div>

templates/base/top_navigation.html
<div class="nav_menu">
    <nav>
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <ul class="nav navbar-nav navbar-left">
                    <li class="dropdown">
                        <a href="#" class="user-profile dropdown-toggle" data-toggle="dropdown"
                           role="button" aria-expanded="false">{{ user.username }} <img class="pull-left"
                                                                                        src="/static/images/gobierno.png"
                                                                                        alt=""> <span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">

                            {% if user.is_authenticated %}
                                {% if perms.contratos_largos.editarUsr %}
                                    <li><a href="{% url 'usuario:usuario_actualizar' user.id %}"><span
                                            class="fa fa-user-edit pull-right"></span>Editar Perfil</a></li>
                                {% endif %}
                            {% endif %}
                            <li><a href="{% url 'logout' %}"><span class="fa fa-sign-out-alt pull-right"></span>Cerrar
                                Sesion</a></li>


                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</div>