apps/admin/urls.py
from django.conf.urls import url,include
from ..admin.views import employee_add,employee_list,employee_delete,employee_edit,PromedioList,add_porcentaje,PromedioDelete

urlpatterns = [
    url(r'^index$', employee_list, name='employee_list'),
    url(r'^add$', employee_add, name="employee_add"),
    #url('<int:id>/details/', employee_details, name="employee_details"),
    url(r'^edit/(?P<id>\d+)/$', employee_edit, name="employee_edit"),
    #url(r'^edit/(?P<id_admin>\d+)/$', employee_edit, name='employee_edit'),
    url(r'^delete/(?P<id>\d+)/$', employee_delete, name="employee_delete"),

    #prmedio
    url(r'^listar$', PromedioList.as_view(), name='promedio_listar'),
    url(r'^nuevo/$',add_porcentaje, name='porcentaje_crear'),
    # url(r'^add/$', views.add_porcentaje, name='padd'),
    url(r'^eliminar/(?P<pk>\d+)/$', PromedioDelete.as_view(), name='promedio_eliminar'),
]

apps/contratos_largos/urls.py
from django.conf.urls import url,include
from .ajax import get_municipios
from django.contrib.auth.decorators import login_required
from ..contratos_largos.views import index,select_view,selectcor_view,contrato_delete,contrato_edit,modificarmodal, \
    ContratoList,ContratoCrear,ContratoUpdate,ContratoDelete,search,principal,ContratoCrearCorto,ReporteViaticosEmp,buscar,login_request

from .views import buscar,buscar1,buscarContrato,ReportAnual

urlpatterns = [
    url(r'^$', login_required(index),name='index'),
    url(r'^nuevo$', login_required(select_view), name='contratolargo_crear'),
    url(r'^nuevocorto$', login_required(selectcor_view), name='contratolargo_crear_corto'),
    url(r'^buscar/$',login_required(search), name='buscar'),
    url(r'^buscarClas/$',login_required(buscar.as_view()), name='buscarClas'),
    url(r'^buscarUsr/$',login_required(buscar1.as_view()), name='buscarUsr'),
    url(r'^principal/',login_required(principal), name='principal'),

    url(r'^eliminar/(?P<pk>\d+)/$', login_required(ContratoDelete.as_view()), name='contratolargo_eliminar'),
    url(r'^editar/(?P<id_contratolargo>\d+)/$', login_required(contrato_edit), name='contratolargo_actualizar'),
    url(r'^ajax/get_municipios/$', login_required(get_municipios), name='get_municipios'),
    url(r'^mod/(?P<id_contratolargo>\d+)/$',login_required(modificarmodal), name='modificar'),
    url(r'^buscarContrato/$',login_required(buscarContrato),name='buscarContrato'),
    url(r'^reporte/(?P<idlugar>[-\w]+)/(?P<idfecha_inicial>[-\w]+)/(?P<idfecha_final>[-\w]+)/$', ReporteViaticosEmp.as_view(), name='reportes'),
    url(r'^reportes/(?P<idlugar>[-\w]+)/(?P<idfecha_inicial>.+?)/(?P<idfecha_final>.+?)/$', login_required(ReportAnual.as_view()), name='reporte_anual_operador'),    

]

reservas/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib import admin
from apps.contratos_largos.views import login_request
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login,logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete

urlpatterns = [
    url(r'^$',RedirectView.as_view(pattern_name='login',permanent=False)),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login_request, name='login'),
    url(r'^contratolargo/', include('apps.contratos_largos.urls', namespace="contratolargo")),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
    url(r'^admin/', include('apps.admin.urls', namespace="administrador")),
]

apps/contratos_largos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import F
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User


# Create your models here.


class Lugar(models.Model):
    name = models.CharField(max_length=80)

    # personal = models.ForeignKey(User)
    def __str__(self):
        return '{}'.format(self.name)


class Espacio(models.Model):
    name = models.CharField(max_length=80)
    estado = models.ForeignKey(Lugar, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.name)


class promediomulta(models.Model):
    valor = models.FloatField(max_length=7)

    def __str__(self):
        return '{}'.format(self.valor)

    class Meta:
        ordering = ["id"]


class ContratoLargo(models.Model):
    # si no hay id tonce django lo pone autoincrementable
    id = models.AutoField(max_length=10, primary_key=True)
    user = models.ForeignKey(User)
    nombre = models.CharField(max_length=50, blank=True)
    dni_nit = models.BigIntegerField(null=True, validators=[MaxValueValidator(10000000000), MinValueValidator(0)])
    fecha_inicial = models.DateTimeField(max_length=16)
    fecha_final = models.DateTimeField(max_length=16)
    fecha_deposito = models.DateTimeField(max_length=16)
    monto_total = models.BigIntegerField(null=True, validators=[MinValueValidator(1)])
    monto_depositado = models.BigIntegerField(null=True,
                                              validators=[MaxValueValidator(monto_total), MinValueValidator(1)])
    monto_faltante = models.BigIntegerField(null=True, validators=[MinValueValidator(0)])
    nombre_completo_actividad = models.CharField(max_length=255, blank=True)
    numero_factura = models.CharField(max_length=25)
    numero_deposito = models.CharField(max_length=25)

    # numero_factura = models.BigIntegerField(null=True,validators=[MaxValueValidator(10000000000),MinValueValidator(0)])
    # numero_deposito = models.BigIntegerField(null=True,validators=[MaxValueValidator(10000000000),MinValueValidator(0)])
    # lugar = models.ForeignKey(Lugar,null=True,blank=True)
    lugar = models.IntegerField(null=True, blank=True)
    espacio = models.ForeignKey(Espacio, null=True, blank=True)
    estado = models.BooleanField(default=True)
    porcentaje_multa = models.ForeignKey(promediomulta, null=True, blank=True)
    mult_dia = models.PositiveIntegerField(null=True)

    #
    def __str__(self):
        return "%s" % self.nombre_completo_actividad

    class Meta:
        ordering = ["id"]
        permissions = (
            ('ver_formLic', 'ver formulario licenciada'),
            ('ver_formUsr', 'Ver formulario usuario'),
            ('editarUsr', 'Ver editar usuario'),
            ('Registrar', 'insertar registros'),
            ('FiltroLIc', 'filtrado fechas lugar'),
            # permisos por url
            ('permiso_url_listlicenciada', 'permisos de url en listar licenciada'),
            ('permiso_url_listusuario', 'permisos de url en listar usuario'),
            ('permiso_url_crear_registros', 'permisos de url en crear usuario'),

        )


# ContratoLargo.objects.values('monto_faltante').annotate(resta=int('monto_total') - int('monto_depositado'))
class User_lugar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # user = models.OneToOneField(User,on_delete=models.CASCADE)
    lugar_trabajo = models.ForeignKey(Lugar, on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % self.lugar_trabajo

templates/contratos_largos/contrato_delete.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <form role="form" action="{% url 'administrador:promedio_listar' object_list.id %}" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <div style="text-align: center">
                    <h3>¿Desea eliminar la reserva de {{ object.id }}?</h3>

                </div>
                <br>

                <div style="text-align: center">
                    <button class="btn btn-danger" type="submit">Si, eliminar</button>
                    <button type="button" class="btn btn-default" onclick="return cerrar_modal()">
                        Cancelar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

templates/contratos_largos/contrato_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Form Validation {% endblock title %}
{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">
                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-danger {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Formulario de Registro <small>Contratos</small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="row">
                        <form method="post">
                            {% csrf_token %}
                            <!-- form input mask -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.nombre |as_crispy_field }}
                                            {{ form.dni_nit |as_crispy_field }}
                                            {{ form.fecha_inicial |as_crispy_field }}
                                            {{ form.fecha_final |as_crispy_field }}
                                            {{ form.fecha_deposito |as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form input mask -->
                            <!-- form color picker -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.porcentaje_multa|as_crispy_field }}
                                            {{ form.monto_total |as_crispy_field }}
                                            {{ form.monto_depositado |as_crispy_field }}
                                            {{ form.estado |as_crispy_field }}
                                            {{ form.nombre_completo_actividad |as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form color picker -->
                            <!-- form color picker -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.numero_factura |as_crispy_field }}
                                            {{ form.numero_deposito |as_crispy_field }}
                                            {{ form.lugar |as_crispy_field }}
                                            {{ form.espacio |as_crispy_field }}
                                        </div>
                                        <div class="col-md-4 col-sm-4 col-xs-4"
                                             style="width: 100%; float: left;margin-top: 25px">
                                            <button type="submit" class="btn btn-primary">Guardar</button>
                                            <a class="btn btn-success" href="{% url 'contratolargo:buscarUsr' %}">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form color picker -->
                        </form>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}
{% block javascripts %}

    <script>//vaciar el select sea o no sea exitosa el envio del formulario
    function removeOptions(selectbox) {
        var i;
        for (i = selectbox.options.length - 1; i >= 0; i--) {
            selectbox.remove(i);
        }
    }

    removeOptions(document.getElementById("id_espacio"));
    </script>


    <script src="/static/vendors/js/jquery.min.js"></script>
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_lugar").on("change", getEspacio);
        });

        function getEspacio() {
            var estadoId = $("#id_lugar").val();
            if (estadoId) {
                // Eliminamos las opciones anteriores del select
                $("#id_espacio").html("");
                var request = $.ajax({
                    type: "GET",
                    url: "{% url 'contratolargo:get_municipios' %}",
                    data: {
                        "lugar_id": estadoId,
                    },
                });
                request.done(function (response) {
                    // Agregamos los resultados al select
                    $("#id_espacio").html(response.municipios);
                    //$("#id_municipio").trigger("change");
                    $("#id_espacio").trigger("change");
                });
            } else {
                $("#id_espacio").html("<option value='' selected='selected'>---------------</option>");
                $("#id_espacio").trigger("change");
            }
        }
    </script>
    <!-- validator -->
{% endblock javascripts %}
{% block calendario %}
    {{ block.super }}
{% endblock %}

templates/contratos_largos/contrato_formcort.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Form Validation {% endblock title %}
{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">

                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-danger {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}

                                </div>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Formulario de Registro <small>Reservas</small></h2>
                            <ul class="nav navbar-right panel_toolbox"></ul>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="row">
                        <form method="post">
                            {% csrf_token %}
                            <!-- form input mask -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.nombre |as_crispy_field }}
                                            {{ form.dni_nit |as_crispy_field }}
                                            {{ form.fecha_inicial |as_crispy_field }}
                                            {{ form.fecha_final |as_crispy_field }}
                                            {{ form.fecha_deposito |as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form input mask -->
                            <!-- form color picker -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.monto_total |as_crispy_field }}
                                            {{ form.monto_depositado |as_crispy_field }}
                                            {{ form.nombre_completo_actividad |as_crispy_field }}
                                            {{ form.numero_factura |as_crispy_field }}
                                            {{ form.numero_deposito |as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form color picker -->
                            <!-- form color picker -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.lugar |as_crispy_field }}
                                            {{ form.espacio |as_crispy_field }}
                                        </div>
                                        <div class="col-md-4 col-sm-4 col-xs-4"
                                             style="width: 100%; float: left;margin-top: 25px">
                                            <button type="submit" class="btn btn-primary ">Guardar</button>
                                            <a class="btn btn-success" href="{% url 'contratolargo:buscarUsr' %}">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form color picker -->
                        </form>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}
{% block javascripts %}
    <script src="/static/vendors/js/jquery.min.js"></script>
    {{ block.super }}
    <script>//vaciar el select sea o no sea exitosa el envio del formulario
    function removeOptions(selectbox) {
        var i;
        for (i = selectbox.options.length - 1; i >= 0; i--) {
            selectbox.remove(i);
        }
    }

    removeOptions(document.getElementById("id_espacio"));
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_lugar").on("change", getEspacio);
        });

        function getEspacio() {
            var estadoId = $("#id_lugar").val();
            if (estadoId) {
                // Eliminamos las opciones anteriores del select
                $("#id_espacio").html("");
                var request = $.ajax({
                    type: "GET",
                    url: "{% url 'contratolargo:get_municipios' %}",
                    data: {
                        "lugar_id": estadoId,
                    },
                });
                request.done(function (response) {
                    // Agregamos los resultados al select
                    $("#id_espacio").html(response.municipios);
                    //$("#id_municipio").trigger("change");
                    $("#id_espacio").trigger("change");
                });
            } else {
                $("#id_espacio").html("<option value='' selected='selected'>---------------</option>");
                $("#id_espacio").trigger("change");
            }
        }
    </script>
    <!-- validator -->
{% endblock javascripts %}

templates/contratos_largos/modificar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Form Validation {% endblock title %}
{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">
                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-danger {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Formulario de Registro <small>Contratos</small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                            </ul>
                            <div class="clearfix"></div>
                        </div>

                    </div>
                    <div class="row">
                        <form method="post">
                            {% csrf_token %}
                            <!-- form input mask -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.nombre |as_crispy_field }}
                                            {{ form.dni_nit |as_crispy_field }}
                                            {{ form.fecha_inicial |as_crispy_field }}
                                            {{ form.fecha_final |as_crispy_field }}
                                            {{ form.fecha_deposito |as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form input mask -->
                            <!-- form color picker -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {% if porcentaje %}
                                                {{ form.porcentaje_multa|as_crispy_field }}
                                            {% else %}
                                                {{ form.porcentaje_multa|as_crispy_field }}
                                            {% endif %}
                                            {{ form.monto_total |as_crispy_field }}
                                            {{ form.monto_depositado |as_crispy_field }}
                                            {{ form.estado |as_crispy_field }}
                                            {{ form.nombre_completo_actividad |as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form color picker -->
                            <!-- form color picker -->
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4" style="width: 100%; float: left; ">
                                            {{ form.numero_factura |as_crispy_field }}
                                            {{ form.numero_deposito |as_crispy_field }}
                                            {{ form.lugar |as_crispy_field }}
                                            {{ form.espacio |as_crispy_field }}
                                        </div>
                                        <div class="col-md-4 col-sm-4 col-xs-4"
                                             style="width: 100%; float: left;margin-top: 25px">
                                            <button type="submit" class="btn btn-primary">Guardar</button>
                                            <a class="btn btn-success" href="{% url 'contratolargo:buscarUsr' %}">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /form color picker -->
                        </form>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}
{% block javascripts %}

    <script src="/static/vendors/js/jquery.min.js"></script>
    {{ block.super }}
    <script>//vaciar el select sea o no sea exitosa el envio del formulario
    function removeOptions(selectbox) {
        var i;
        for (i = selectbox.options.length - 1; i >= 0; i--) {
            selectbox.remove(i);
        }
    }

    removeOptions(document.getElementById("id_espacio"));
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_lugar").on("change", getEspacio);
        });

        function getEspacio() {
            var estadoId = $("#id_lugar").val();
            if (estadoId) {
                // Eliminamos las opciones anteriores del select
                $("#id_espacio").html("");
                var request = $.ajax({
                    type: "GET",
                    url: "{% url 'contratolargo:get_municipios' %}",
                    data: {
                        "lugar_id": estadoId,
                    },
                });
                request.done(function (response) {
                    // Agregamos los resultados al select
                    $("#id_espacio").html(response.municipios);
                    //$("#id_municipio").trigger("change");
                    $("#id_espacio").trigger("change");
                });
            } else {
                $("#id_espacio").html("<option value='' selected='selected'>---------------</option>");
                $("#id_espacio").trigger("change");
            }
        }
    </script>
    <!-- validator -->
{% endblock javascripts %}
{% block calendario %}
    {{ block.super }}
{% endblock %}