apps/admin/urls.py
from django.conf.urls import url,include
from ..admin.views import employee_add,employee_list,employee_delete,employee_edit,PromedioList,add_porcentaje,PromedioDelete

urlpatterns = [
    url(r'^index$', employee_list, name='employee_list'),
    url(r'^add$', employee_add, name="employee_add"),
    #url('<int:id>/details/', employee_details, name="employee_details"),
    url(r'^edit/(?P<id>\d+)/$', employee_edit, name="employee_edit"),
    #url(r'^edit/(?P<id_admin>\d+)/$', employee_edit, name='employee_edit'),
    url(r'^delete/(?P<id>\d+)/$', employee_delete, name="employee_delete"),

    #prmedio
    url(r'^listar$', PromedioList.as_view(), name='promedio_listar'),
    url(r'^nuevo/$',add_porcentaje, name='porcentaje_crear'),
    # url(r'^add/$', views.add_porcentaje, name='padd'),
    url(r'^eliminar/(?P<pk>\d+)/$', PromedioDelete.as_view(), name='promedio_eliminar'),
]

reservas/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib import admin
from apps.contratos_largos.views import login_request
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login,logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete

urlpatterns = [
    url(r'^$',RedirectView.as_view(pattern_name='login',permanent=False)),
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login_request, name='login'),
    url(r'^contratolargo/', include('apps.contratos_largos.urls', namespace="contratolargo")),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
    url(r'^admin/', include('apps.admin.urls', namespace="administrador")),
]

templates/employee/add.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Principal {% endblock title %}
{% block stylesheets %}
    {{ block.super }}
    <style>
        .centered {
            text-align: center;
        }
    </style>
{% endblock stylesheets %}
{% block content %}
    <div style="height:100%" class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">

                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-success {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}

                                </div>
                            {% endfor %}


                        </ul>
                    {% endif %}
                </div>
            </div>

            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>CREAR USUARIO <small></small></h2>
                            <div class="clearfix"></div>
                        </div>

                    </div>
                    <div class="x_content">
                        <form method="post">
                            {% csrf_token %}
                            <!-- form input mask -->
                            <div class="col-md-4 col-sm-4 col-xs-4 col-sm-offset-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-6 col-sm-6 col-xs-6" style="width: 100%;  ">
                                            {{ user_form.first_name |as_crispy_field }}
                                            {{ user_form.last_name |as_crispy_field }}
                                            {{ user_form.email |as_crispy_field }}
                                            {{ user_form.username |as_crispy_field }}
                                            {{ user_form.password |as_crispy_field }}
                                        </div>
                                        <div class="col-md-4 col-sm-4 col-xs-4">
                                            <button type="submit" class="btn btn-success float-right"
                                                    style="margin-top: 25px">Enviar
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascripts %}
    {{ block.super }}
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
{% endblock javascripts %}

templates/employee/delete.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Form Validation {% endblock title %}
{% block content %}
    <style>

    </style>
    <div class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">

                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-danger {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}

                                </div>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 ">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>ELIMINAR USUARIO! <small></small></h2>
                            <ul class="nav navbar-right panel_toolbox"></ul>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="row">
                        <form method="post">
                            {% csrf_token %}
                            <!-- form input mask -->
                            <div class="col-md-4 col-sm-4 col-xs-4 col-sm-offset-4">
                                <div class="x_panel">
                                    <div class="x_title" style="text-align: center">

                                        <h4>Deseas eliminar a este usuario?</h4>
                                    </div>
                                    <div class="x_content">
                                        <div class="col-md-4 col-sm-4 col-xs-4 " style="width: 100%;  ">
                                            <br>


                                            <div style="text-align: center">
                                                <h2>{{ user.first_name }} &nbsp; {{ user.last_name }}</h2>
                                            </div>
                                            <form method="post">
                                                {% csrf_token %}
                                                <div style="text-align: center; margin-top: 25px">
                                                    <input class="btn btn-danger" type="submit" value="Si,Eliminar">
                                                </div>

                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}
{% block javascripts %}
    <script src="/static/vendors/js/jquery.min.js"></script>
    {{ block.super }}

    <!-- validator -->
{% endblock javascripts %}

templates/employee/edit.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Principal {% endblock title %}
{% block content %}
    <div style="height:100%" class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">

                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-success {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}

                                </div>
                            {% endfor %}


                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>PRINCIPAL <small></small></h2>
                            <div class="clearfix"></div>
                        </div>

                    </div>
                    <div class="x_content">
                        <form method="post">
                            {% csrf_token %}
                            <!-- form input mask -->
                            <div class="col-md-4 col-sm-4 col-xs-4 col-sm-offset-4">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="col-md-6 col-sm-6 col-xs-6" style="width: 100%;  ">
                                            {{ user_form.first_name |as_crispy_field }}
                                            {{ user_form.last_name |as_crispy_field }}
                                            {{ user_form.email |as_crispy_field }}
                                            {{ user_form.username |as_crispy_field }}
                                            {{ user_form.password |as_crispy_field }}
                                        </div>
                                        <div class="col-md-4 col-sm-4 col-xs-4">
                                            <button type="submit" class="btn btn-success float-right">Actualizar
                                                Informacion
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascripts %}
    {{ block.super }}
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
{% endblock javascripts %}

templates/employee/index.html
{% extends "base/base.html" %}
{% block title %} Principal {% endblock title %}
{% block stylesheets %}
    {{ block.super }}
    <style>
        .centered {
            text-align: center;
        }
    </style>
{% endblock stylesheets %}
{% block content %}
    <div style="height:100%" class="right_col" role="main">
        <div class="">
            <div class="row">
                <div class="col-md-4 col-sm-offset-8">
                    {% if messages %}
                        <ul class="message">

                            {% for message in messages %}
                                <div style="text-align: center"
                                     class="alert alert-success {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <a href="#" class="del-msg">&times;</a>
                                    </button>
                                    {{ message }}

                                </div>
                            {% endfor %}


                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="page-title">
                <div class="title_right">
                    <h3>Gobierno Autonomo Departamental de Potosi </h3>
                </div>
            </div>
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>USUARIOS <small></small></h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">


                                <div class="table-responsive">
                                    <div class="col-md-12 col-sm-12 col-xs-12"></div>
                                    <table align="center" border="1" height=60 width="100%" id="datatable"
                                           class="table table-striped jambo_table bulk_action table-bordered center-all ">
                                        <thead>
                                        <tr>
                                            <th id="center">N°
                                            </td>
                                            <td id="center">Nombres</td>
                                            <td id="center">Apellidos</td>
                                            <th id="center">Correo Electronico</th>
                                            <th id="center">Usuario</th>
                                            <th id="center">Contraseña</th>
                                            <th id="center">Acciones</th>

                                        </tr>
                                        </thead>
                                        <tbody id="tags1">
                                        {% if users %}
                                            {% for user in users %}
                                                <tr style="vertical-align: middle;">
                                                    <td id="center">{{ user.id }}</td>
                                                    <td id="center">{{ user.first_name }}</td>
                                                    <td id="center">{{ user.last_name }}</td>
                                                    <td id="center">{{ user.email }}</td>
                                                    <td id="center">{{ user.username }}</td>
                                                    <td id="center">{{ user.password }} </td>
                                                    <td id="center">
                                                        <div style="display: flex; ">
                                                            <div>

                                                                <a style="font-size: 12px;"
                                                                   class="btn btn-info btn-xs preload "
                                                                   href="{% url 'administrador:employee_edit' user.id %}">
                                                                    <span style="color: white;font-size: 10px;"
                                                                          class="glyphicon glyphicon-pencil "></span>
                                                                    Editar</a>
                                                            </div>
                                                            <div>
                                                                <a style="font-size: 12px;"
                                                                   class="btn btn-danger btn-xs"
                                                                   href="{% url 'administrador:employee_delete' user.id %}">
                                                                    <span style="color: white;font-size: 10px;"
                                                                          class="glyphicon glyphicon-trash"></span>
                                                                    Borrar</a>
                                                            </div>
                                                        </div>
                                                    </td>

                                                </tr>

                                            {% endfor %}
                                            </tbody>
                                            </table>
                                        {% else %}
                                            <p>There is no employee available.</p>
                                        {% endif %}

                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascripts %}
    {{ block.super }}
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
    <script>

        $('#datatable').DataTable({
            "searching": false,
            "paging": true,
            "ordering": false,
            "info": false,
            "bFilter": false,
            "bLengthChange": false,
            language: {
                "decimal": "",
                "emptyTable": "No hay información",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Entradas",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
        });
    </script>
    <script>
        function abrir_modal(url) {
            $('#popup').load(url, function () {
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal() {
            $('#popup').modal('hide');
            return false;
        }
    </script>
{% endblock javascripts %}